/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/ai/': RouteRecordInfo<'/admin/ai/', '/admin/ai', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/datasetShow/': RouteRecordInfo<'/admin/datasetShow/', '/admin/datasetShow', Record<never, never>, Record<never, never>>,
    '/admin/history/': RouteRecordInfo<'/admin/history/', '/admin/history', Record<never, never>, Record<never, never>>,
    '/admin/modelParameter/': RouteRecordInfo<'/admin/modelParameter/', '/admin/modelParameter', Record<never, never>, Record<never, never>>,
    '/admin/promoteKnowledge/': RouteRecordInfo<'/admin/promoteKnowledge/', '/admin/promoteKnowledge', Record<never, never>, Record<never, never>>,
    '/admin/userManage/': RouteRecordInfo<'/admin/userManage/', '/admin/userManage', Record<never, never>, Record<never, never>>,
    '/auth/login/': RouteRecordInfo<'/auth/login/', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/Register/': RouteRecordInfo<'/auth/Register/', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/detection/': RouteRecordInfo<'/detection/', '/detection', Record<never, never>, Record<never, never>>,
    '/history/': RouteRecordInfo<'/history/', '/history', Record<never, never>, Record<never, never>>,
    '/knowledge/': RouteRecordInfo<'/knowledge/', '/knowledge', Record<never, never>, Record<never, never>>,
    '/stats/': RouteRecordInfo<'/stats/', '/stats', Record<never, never>, Record<never, never>>,
    '/userInfo/': RouteRecordInfo<'/userInfo/', '/userInfo', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/admin/ai/index.vue': {
      routes: '/admin/ai/'
      views: never
    }
    'src/pages/admin/dashboard/index.vue': {
      routes: '/admin/dashboard/'
      views: never
    }
    'src/pages/admin/datasetShow/index.vue': {
      routes: '/admin/datasetShow/'
      views: never
    }
    'src/pages/admin/history/index.vue': {
      routes: '/admin/history/'
      views: never
    }
    'src/pages/admin/modelParameter/index.vue': {
      routes: '/admin/modelParameter/'
      views: never
    }
    'src/pages/admin/promoteKnowledge/index.vue': {
      routes: '/admin/promoteKnowledge/'
      views: never
    }
    'src/pages/admin/userManage/index.vue': {
      routes: '/admin/userManage/'
      views: never
    }
    'src/pages/auth/login/index.vue': {
      routes: '/auth/login/'
      views: never
    }
    'src/pages/auth/Register/index.vue': {
      routes: '/auth/Register/'
      views: never
    }
    'src/pages/detection/index.vue': {
      routes: '/detection/'
      views: never
    }
    'src/pages/history/index.vue': {
      routes: '/history/'
      views: never
    }
    'src/pages/knowledge/index.vue': {
      routes: '/knowledge/'
      views: never
    }
    'src/pages/stats/index.vue': {
      routes: '/stats/'
      views: never
    }
    'src/pages/userInfo/index.vue': {
      routes: '/userInfo/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
